---
openapi: "3.0.3"
info:
  title: "SERVICE PROVIDER MANAGEMENT REST API"
  description: "API for managing service provider"
  version: "0.0.1-SNAPSHOT"
paths:
  /service-provider:
    post:
      tags:
      - "ServiceProvider"
      summary: "Become Service Provider"
      description: "Become Service Provider"
      operationId: "becomeServiceProvider"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ServiceProviderRegister"
      responses:
        "201":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreationResponse"
        "404":
          description: "SERVICE_PROVIDER_404_001"
        "409":
          description: "SERVICE-PROVIDER_409_001"
components:
  schemas:
    ServiceProviderRegister:
      required:
      - "phoneNumber"
      - "city"
      - "district"
      - "serviceType"
      type: "object"
      properties:
        city:
          type: "string"
          format: "uuid"
        district:
          type: "string"
          format: "uuid"
        phoneNumber:
          $ref: "#/components/schemas/PhoneNumber"
        serviceType:
          $ref: "#/components/schemas/ServiceType"
    PhoneNumber:
      type: "object"
      required:
      - "countryCode"
      - "number"
      properties:
        countryCode:
          type: "string"
        number:
          type: "string"
    ServiceType:
      type: "object"
      required:
      - "id"
      - "yearOfExperience"
      - "document"
      properties:
        id:
          type: "string"
          format: "uuid"
        yearOfExperience:
          type: "integer"
        document:
          type: "string"
          format: "uuid"
    CreationResponse:
      type: "object"
      required:
      - "newId"
      properties:
        newId:
          type: "string"
          format: "uuid"
